### PR TITLE
Update instructions with devcontainers-cli and update default workspace mount

### PR DESCRIPTION
**Pull request by mcarfagno**
### What's New

- Adds a writeup on how to use the [cli version of devcontainers](https://github.com/devcontainers/cli) 

  Tested myself. For reference, this is what happens at each step:

<details>

<summary>devcontainer up</summary>

```
[1 ms] @devcontainers/cli 0.59.1. Node.js v22.4.1. linux 6.9.9-arch1-1 x64.
[431 ms] Start: Run: docker-compose -f /home/marcello/ros2_tools/ros2_dev_container/.devcontainer/docker-compose.base.yml -f /home/marcello/ros2_tools/ros2_dev_container/.devcontainer/docker-compose.cv.yml -f /home/marcello/ros2_tools/ros2_dev_container/.devcontainer/docker-compose.dev.yml --profile * config
[496 ms] Start: Run: docker-compose -f /home/marcello/ros2_tools/ros2_dev_container/.devcontainer/docker-compose.base.yml -f /home/marcello/ros2_tools/ros2_dev_container/.devcontainer/docker-compose.cv.yml -f /home/marcello/ros2_tools/ros2_dev_container/.devcontainer/docker-compose.dev.yml --profile * config
[540 ms] name: devcontainer
services:
  base:
    build:
      context: /home/marcello/ros2_tools/ros2_dev_container/.devcontainer
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: jazzy
      target: ros2_base
    environment:
      DISPLAY: :0
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: "1"
    image: ros2_base
    networks:
      default: null
  computer_vision:
    build:
      context: /home/marcello/ros2_tools/ros2_dev_container/.devcontainer
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: jazzy
      target: ros2_cv
    environment:
      DISPLAY: :0
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: "1"
    image: ros2_cv
    networks:
      default: null
  dev:
    build:
      context: /home/marcello/ros2_tools/ros2_dev_container/.devcontainer
      dockerfile: Dockerfile
      args:
        GROUP_ID: "1000"
        GROUP_NAME: marcello
        ROS_DISTRO: jazzy
        USER_ID: "1000"
        USER_NAME: marcello
      target: ros2_dev
    cap_add:
      - SYS_PTRACE
    environment:
      DISPLAY: :0
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: "1"
    image: ros2_dev
    ipc: host
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    user: marcello
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        bind:
          create_host_path: true
      - type: bind
        source: /home/marcello/.ssh
        target: /home/marcello/.ssh
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /home/marcello/data
        target: /home/marcello/data
        bind:
          create_host_path: true
      - type: bind
        source: /dev/bus/usb
        target: /dev/bus/usb
        bind:
          create_host_path: true
      - type: bind
        source: /home/marcello/ros2_tools/ros2_dev_container/workspaces
        target: /home/marcello/workspaces
        bind:
          create_host_path: true
networks:
  default:
    name: devcontainer_default
[543 ms] Start: Run: docker inspect --type image ros:jazzy
[8079 ms] Docker Compose override file for building image:
services:
  dev:
    build:
      dockerfile: /tmp/devcontainercli-marcello/container-features/0.59.1-1721306450515/Dockerfile-with-features
      target: dev_containers_target_stage
      args:
        - BUILDKIT_INLINE_CACHE=1
        - _DEV_CONTAINERS_BASE_IMAGE=ros2_dev

[8081 ms] Start: Run: docker-compose --project-name ros2_dev_container_devcontainer -f /home/marcello/ros2_tools/ros2_dev_container/.devcontainer/docker-compose.base.yml -f /home/marcello/ros2_tools/ros2_dev_container/.devcontainer/docker-compose.cv.yml [+] Building 217.8s (20/31)                                                                                                                                                                                                                    docker:default
 => [computer_vision internal] load .dockerignore                                                                                                                                                                                                        0.1s
 => => transferring context: 2B                                                                                                                                                                                                                          0.0s
 => [dev internal] load .dockerignore                                                                                                                                                                                                                    0.1s
 => => transferring context: 2B                                                                                                                                                                                                                          0.0s
 => [base internal] load build context                                                                                                                                                                                                                   0.2s
 => => transferring context: 118B                                                                                                                                                                                                                        0.2s
 => [dev ros2_base 1/6] FROM docker.io/library/ros:jazzy@sha256:ee4862fe098e18eba8fb0e9843d57241e404aea12bcba57ed037827f16d98ba6                                                                                                                        27.3s
 => => resolve docker.io/library/ros:jazzy@sha256:ee4862fe098e18eba8fb0e9843d57241e404aea12bcba57ed037827f16d98ba6                                                                                                                                       0.0s
 => => sha256:2abc93103cd31210b12722889bc8abe192c394119b2c3d88dbe2db4bdf2d31da 3.09kB / 3.09kB                                                                                                                                                           0.0s
 => => sha256:ee4862fe098e18eba8fb0e9843d57241e404aea12bcba57ed037827f16d98ba6 2.69kB / 2.69kB                                                                                                                                                           0.0s
 => => sha256:08803d401c081fc3d12416d99b187a634698db36a10df80f4cef29170ef83e5b 681.84kB / 681.84kB                                                                                                                                                       0.8s
 => => sha256:62a2e7a7eb8562d26a6e6ad257298e986eaac4578a115c8e1bdcc9eb81a5832c 5.60kB / 5.60kB                                                                                                                                                           0.0s
 => => sha256:49f68a5436d21a97e82cf7e242efe03dde4f5b729ed2dbaf097fa8087d993f1c 3.56MB / 3.56MB                                                                                                                                                           0.5s
 => => sha256:9c704ecd0c694c4cbdd85e589ac8d1fc3fd8f890b7f3731769a5b169eb495809 29.71MB / 29.71MB                                                                                                                                                         3.0s
 => => sha256:c36adc7815cbb0b60279e15f0898d1f5d3880e45c336e2d37b6e55f3c19a7d41 2.00kB / 2.00kB                                                                                                                                                           0.8s
 => => sha256:f6dd0181ad8621c2a9206894fa0ac8823b0e7b0c1e07f8700418d53b93a2fa76 273B / 273B                                                                                                                                                               1.0s
 => => sha256:47b76af7af5fdf91bcc77e8167917c7c9febf10158f328daafe713d29813881e 122.46MB / 122.46MB                                                                                                                                                      13.9s
 => => sha256:d79ae2ca4e9abcb78cdac5210d4cbcc57bb261e4fd8cca1695e8606c8e4193be 197B / 197B                                                                                                                                                               1.3s
 => => sha256:f5321657307942f41a64bc471813d51df34d29ad63ad10c3d793023b9021fe79 114.11MB / 114.11MB                                                                                                                                                      16.5s
 => => extracting sha256:9c704ecd0c694c4cbdd85e589ac8d1fc3fd8f890b7f3731769a5b169eb495809                                                                                                                                                                1.4s
 => => sha256:86be0739349eff42b0a8e0e345e9e9a8aa166f249d7f6ef37b687d356f47b3b6 320.66kB / 320.66kB                                                                                                                                                       3.3s
 => => sha256:a3cb43da572f51f6a10a289760b4f513838dcd8847ee4d4f6192252fc22c8ea4 2.45kB / 2.45kB                                                                                                                                                           3.5s
 => => sha256:8b8529e63f95c2d883fe2a372f6ab67e93846ac82959ffd623ca33286548c9db 27.53MB / 27.53MB                                                                                                                                                         8.1s
 => => extracting sha256:08803d401c081fc3d12416d99b187a634698db36a10df80f4cef29170ef83e5b                                                                                                                                                                0.1s
 => => extracting sha256:49f68a5436d21a97e82cf7e242efe03dde4f5b729ed2dbaf097fa8087d993f1c                                                                                                                                                                0.1s
 => => extracting sha256:c36adc7815cbb0b60279e15f0898d1f5d3880e45c336e2d37b6e55f3c19a7d41                                                                                                                                                                0.0s
 => => extracting sha256:f6dd0181ad8621c2a9206894fa0ac8823b0e7b0c1e07f8700418d53b93a2fa76                                                                                                                                                                0.0s
 => => extracting sha256:47b76af7af5fdf91bcc77e8167917c7c9febf10158f328daafe713d29813881e                                                                                                                                                                6.7s
 => => extracting sha256:d79ae2ca4e9abcb78cdac5210d4cbcc57bb261e4fd8cca1695e8606c8e4193be                                                                                                                                                                0.0s
 => => extracting sha256:f5321657307942f41a64bc471813d51df34d29ad63ad10c3d793023b9021fe79                                                                                                                                                                3.9s
 => => extracting sha256:86be0739349eff42b0a8e0e345e9e9a8aa166f249d7f6ef37b687d356f47b3b6                                                                                                                                                                0.0s
 => => extracting sha256:a3cb43da572f51f6a10a289760b4f513838dcd8847ee4d4f6192252fc22c8ea4                                                                                                                                                                0.0s
 => => extracting sha256:8b8529e63f95c2d883fe2a372f6ab67e93846ac82959ffd623ca33286548c9db                                                                                                                                                                1.2s
 => [computer_vision internal] load build context                                                                                                                                                                                                        0.1s
 => => transferring context: 588B                                                                                                                                                                                                                        0.0s
 => [dev internal] load build context                                                                                                                                                                                                                    0.2s
 => => transferring context: 879B                                                                                                                                                                                                                        0.1s
 => [dev ros2_base 2/6] RUN export DEBIAN_FRONTEND=noninteractive                                                                                                                                                                                        0.3s
[+] Building 218.0s (20/31)                                       docker:default- => [dev internal] load .dockerignore                                       0.1s [+] Building 300.8s (33/33) FINISHED                              docker:default  => [base internal] load build definition from Dockerfile                   0.1s
 => => transferring dockerfile: 2.27kB                                      0.0sU => [computer_vision internal] load build definition from Dockerfile        0.0s  => => transferring dockerfile: 2.27kB                                      0.0s  => [dev internal] load build definition from Dockerfile-with-features      0.0s
 => => transferring dockerfile: 2.39kB                                      0.0ss => [dev internal] load metadata for docker.io/library/ros:jazzy            1.6s  => [base internal] load .dockerignore                                      0.0s  => => transferring context: 2B                                             0.0s
 => [computer_vision internal] load .dockerignore                           0.1s  => => transferring context: 2B                                             0.0st => [dev internal] load .dockerignore                                       0.1s  => => transferring context: 2B                                             0.0s
 => [base internal] load build context                                      0.2s  => => transferring context: 118B                                           0.2s  => [dev ros2_base 1/6] FROM docker.io/library/ros:jazzy@sha256:ee4862fe0  27.3s  => => resolve docker.io/library/ros:jazzy@sha256:ee4862fe098e18eba8fb0e98  0.0s
 => => sha256:2abc93103cd31210b12722889bc8abe192c394119b2c 3.09kB / 3.09kB  0.0sp => => sha256:ee4862fe098e18eba8fb0e9843d57241e404aea12bcb 2.69kB / 2.69kB  0.0s  => => sha256:08803d401c081fc3d12416d99b187a634698db36 681.84kB / 681.84kB  0.8s  => => sha256:62a2e7a7eb8562d26a6e6ad257298e986eaac4578a11 5.60kB / 5.60kB  0.0s
 => => sha256:49f68a5436d21a97e82cf7e242efe03dde4f5b729ed2 3.56MB / 3.56MB  0.5st => => sha256:9c704ecd0c694c4cbdd85e589ac8d1fc3fd8f890b7 29.71MB / 29.71MB  3.0sa => => sha256:c36adc7815cbb0b60279e15f0898d1f5d3880e45c336 2.00kB / 2.00kB  0.8s  => => sha256:f6dd0181ad8621c2a9206894fa0ac8823b0e7b0c1e07f870 273B / 273B  1.0s
 => => sha256:47b76af7af5fdf91bcc77e8167917c7c9febf10 122.46MB / 122.46MB  13.9s  => => sha256:d79ae2ca4e9abcb78cdac5210d4cbcc57bb261e4fd8cca16 197B / 197B  1.3s  => => sha256:f5321657307942f41a64bc471813d51df34d29a 114.11MB / 114.11MB  16.5s  => => extracting sha256:9c704ecd0c694c4cbdd85e589ac8d1fc3fd8f890b7f373176  1.4s
 => => sha256:86be0739349eff42b0a8e0e345e9e9a8aa166f24 320.66kB / 320.66kB  3.3s  => => sha256:a3cb43da572f51f6a10a289760b4f513838dcd8847ee 2.45kB / 2.45kB  3.5s  => => sha256:8b8529e63f95c2d883fe2a372f6ab67e93846ac829 27.53MB / 27.53MB  8.1s  => => extracting sha256:08803d401c081fc3d12416d99b187a634698db36a10df80f4  0.1s
 => => extracting sha256:49f68a5436d21a97e82cf7e242efe03dde4f5b729ed2dbaf0  0.1s9 => => extracting sha256:c36adc7815cbb0b60279e15f0898d1f5d3880e45c336e2d37  0.0s  => => extracting sha256:f6dd0181ad8621c2a9206894fa0ac8823b0e7b0c1e07f8700  0.0s  => => extracting sha256:47b76af7af5fdf91bcc77e8167917c7c9febf10158f328daa  6.7s
 => => extracting sha256:d79ae2ca4e9abcb78cdac5210d4cbcc57bb261e4fd8cca169  0.0s  => => extracting sha256:f5321657307942f41a64bc471813d51df34d29ad63ad10c3d  3.9s  => => extracting sha256:86be0739349eff42b0a8e0e345e9e9a8aa166f249d7f6ef37  0.0s  => => extracting sha256:a3cb43da572f51f6a10a289760b4f513838dcd8847ee4d4f6  0.0s
 => => extracting sha256:8b8529e63f95c2d883fe2a372f6ab67e93846ac82959ffd62  1.2s( => [computer_vision internal] load build context                           0.1s  => => transferring context: 588B                                           0.0s  => [dev internal] load build context                                       0.2s
 => => transferring context: 879B                                           0.1s
 => [dev ros2_base 2/6] RUN export DEBIAN_FRONTEND=noninteractive           0.3s. => [computer_vision ros2_base 3/6] RUN apt update -y && apt-get -y instal  9.8s
 => [base ros2_base 4/6] RUN locale-gen en_GB.UTF-8; update-locale LC_ALL=  1.1s
 => [computer_vision ros2_base 5/6] COPY apt-base-packages /tmp/apt-base-p  0.1s
 => [computer_vision ros2_base 6/6] RUN apt-get update &&     apt-get inst  9.1s
 => [dev ros2_cv 1/2] COPY apt-cv-packages /tmp/apt-cv-packages             0.1s
 => CACHED [computer_vision ros2_base 5/6] COPY apt-base-packages /tmp/apt  0.0s
 => CACHED [computer_vision ros2_base 6/6] RUN apt-get update &&     apt-g  0.0s
 => [base] exporting to image                                               1.1s
 => => exporting layers                                                     1.0s
 => => writing image sha256:f163ee6b2525f14a3ed449285fee483f31bd116eb2f0db  0.0s
 => => naming to docker.io/library/ros2_base                                0.0s
 => [dev ros2_cv 2/2] RUN apt-get update &&     apt-get install -y $(cut  215.7s
 => CACHED [dev ros2_base 5/6] COPY apt-base-packages /tmp/apt-base-packag  0.0s
 => CACHED [dev ros2_base 6/6] RUN apt-get update &&     apt-get install -  0.0s
 => CACHED [dev ros2_cv 1/2] COPY apt-cv-packages /tmp/apt-cv-packages      0.0s
 => CACHED [dev ros2_cv 2/2] RUN apt-get update &&     apt-get install -y   0.0s
 => [dev ros2_dev 1/6] COPY apt-dev-packages /tmp/apt-dev-packages          0.1s
 => [computer_vision] exporting to image                                   10.4s
 => => exporting layers                                                    10.3s
 => => writing image sha256:2e4ac601afbe3cddb56338b0188a16701c0dc47ce7529b  0.0s
 => => naming to docker.io/library/ros2_cv                                  0.0s
 => [dev ros2_dev 2/6] RUN apt-get update &&     apt-get install -y $(cut  23.1s
 => [dev ros2_dev 3/6] RUN if getent group 1000 > /dev/null; then     OLD_  3.7s
 => [dev ros2_dev 4/6] RUN sudo usermod --append --groups video marcello    0.4s
 => [dev ros2_dev 5/6] RUN rosdep update                                    4.3s
 => [dev ros2_dev 6/6] RUN echo "source /opt/ros/jazzy/setup.bash" >> /hom  0.3s
 => [dev] exporting to image                                                3.3s
 => => exporting layers                                                     3.3s
 => => preparing layers for inline cache                                    0.0s
 => => writing image sha256:a4c99020e0e5f6a92174cdd602fffc4af95cd322f3cb8e  0.0s
 => => naming to docker.io/library/ros2_dev                                 0.0s
[+] Building 2.7s (6/6) FINISHED                                  docker:default
 => [internal] load build definition from updateUID.Dockerfile-0.59.1       0.0s
 => => transferring dockerfile: 1.52kB                                      0.0s
 => [internal] load metadata for docker.io/library/ros2_dev:latest          0.0s
 => [internal] load .dockerignore                                           0.0s
 => => transferring context: 2B                                             0.0s
 => [1/2] FROM docker.io/library/ros2_dev:latest                            0.4s
 => [2/2] RUN eval $(sed -n "s/marcello:[^:]*:\([^:]*\):\([^:]*\):[^:]*:\(  0.3s
 => exporting to image                                                      1.7s
 => => exporting layers                                                     1.7s
 => => writing image sha256:6460f7af298192a48be4d9ebf80763d02d497fa7d4f31f  0.0s
 => => naming to docker.io/library/vsc-ros2_dev_container-ee18135ea3c51630  0.0s
[311811 ms] Start: Run: docker-compose --project-name ros2_dev_container_devcontainer -f /home/marcello/ros2_tools/ros2_dev_container/.devcontainer/docker-compose.base.yml -f /home/marcello/ros2_tools/ros2_dev_container/.devcontainer/docker-compose.cv.yml -f /home/marcello/ros2_tools/ros2_dev_container/.devcontainer/docker-compose.dev.yml -f /tmp/devcontainercli-marcello/docker-compose/docker-compose.devcontainer.build-1721306450519.yml -f /tmp/devcontainercli-marcello/docker-compose/docker-compose.devcontainer.containerFeatures-1721306754250-959ced00-ab4e-491f-8ad1-078defe038e5.yml up -d
[+] Running 4/4
 ✔ Network ros2_dev_container_devcontainer_default              Created     0.3s
 ✔ Container ros2_dev_container_devcontainer-computer_vision-1  Started     0.5s
 ✔ Container ros2_dev_container_devcontainer-dev-1              Started     0.4s
 ✔ Container ros2_dev_container_devcontainer-base-1             Started     0.5s
{"outcome":"success","containerId":"286cfd5f50fed076f39b708e167b48a76cedadc34503291f983db1ca5d2fbda4","composeProjectName":"ros2_dev_container_devcontainer","remoteUser":"marcello","remoteWorkspaceFolder":"/home/marcello/workspaces/ros2_ws"}

```

</details>

<details>

<summary>devcontainer exec</summary>

```
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

marcello@marcello-xps169640:~/workspaces/ros2_ws$
arcello@marcello-xps169640:~/workspaces/ros2_ws$ ros2 pkg list
action_msgs
actionlib_msgs
ament_clang_format
ament_cmake
ament_cmake_auto
ament_cmake_clang_format
ament_cmake_copyright
ament_cmake_core
ament_cmake_cppcheck
ament_cmake_cpplint
ament_cmake_export_definitions
ament_cmake_export_dependencies
ament_cmake_export_include_directories
ament_cmake_export_interfaces
ament_cmake_export_libraries
ament_cmake_export_link_flags
ament_cmake_export_targets
ament_cmake_flake8
ament_cmake_gen_version_h
ament_cmake_gmock
ament_cmake_gtest
ament_cmake_include_directories
ament_cmake_libraries
ament_cmake_lint_cmake
ament_cmake_pep257
ament_cmake_pytest
ament_cmake_python
ament_cmake_ros
ament_cmake_target_dependencies
ament_cmake_test
ament_cmake_uncrustify
ament_cmake_version
ament_cmake_xmllint
ament_copyright
ament_cppcheck
ament_cpplint
ament_flake8
ament_index_cpp
ament_index_python
ament_lint
ament_lint_auto
ament_lint_cmake
ament_lint_common
ament_package
ament_pep257
ament_uncrustify
ament_xmllint
builtin_interfaces
camera_calibration
camera_calibration_parsers
camera_info_manager
class_loader
common_interfaces
composition_interfaces
console_bridge_vendor
cv_bridge
diagnostic_msgs
domain_coordinator
eigen3_cmake_module
fastrtps_cmake_module
geometry2
geometry_msgs
gz_cmake_vendor
gz_math_vendor
gz_utils_vendor
image_common
image_geometry
image_publisher
image_transport
image_view
interactive_markers
kdl_parser
keyboard_handler
laser_geometry
launch
launch_ros
launch_testing
launch_testing_ament_cmake
launch_testing_ros
launch_xml
launch_yaml
libcurl_vendor
liblz4_vendor
libstatistics_collector
libyaml_vendor
lifecycle_msgs
map_msgs
mcap_vendor
message_filters
nav_msgs
orocos_kdl_vendor
osrf_pycommon
pcl_conversions
pcl_msgs
pluginlib
point_cloud_transport
pybind11_vendor
python_cmake_module
python_qt_binding
qt_dotgraph
qt_gui
rcl
rcl_action
rcl_interfaces
rcl_lifecycle
rcl_logging_interface
rcl_logging_spdlog
rcl_yaml_param_parser
rclcpp
rclcpp_action
rclcpp_components
rclcpp_lifecycle
rclpy
rcpputils
rcutils
resource_retriever
rmw
rmw_dds_common
rmw_fastrtps_cpp
rmw_fastrtps_shared_cpp
rmw_implementation
rmw_implementation_cmake
robot_state_publisher
ros2action
ros2bag
ros2cli
ros2cli_common_extensions
ros2component
ros2doctor
ros2interface
ros2launch
ros2lifecycle
ros2multicast
ros2node
ros2param
ros2pkg
ros2run
ros2service
ros2topic
ros_base
ros_core
ros_environment
ros_workspace
rosbag2
rosbag2_compression
rosbag2_compression_zstd
rosbag2_cpp
rosbag2_interfaces
rosbag2_py
rosbag2_storage
rosbag2_storage_default_plugins
rosbag2_storage_mcap
rosbag2_storage_sqlite3
rosbag2_transport
rosgraph_msgs
rosidl_adapter
rosidl_cli
rosidl_cmake
rosidl_core_generators
rosidl_core_runtime
rosidl_default_generators
rosidl_default_runtime
rosidl_dynamic_typesupport
rosidl_dynamic_typesupport_fastrtps
rosidl_generator_c
rosidl_generator_cpp
rosidl_generator_py
rosidl_generator_type_description
rosidl_parser
rosidl_pycommon
rosidl_runtime_c
rosidl_runtime_cpp
rosidl_runtime_py
rosidl_typesupport_c
rosidl_typesupport_cpp
rosidl_typesupport_fastrtps_c
rosidl_typesupport_fastrtps_cpp
rosidl_typesupport_interface
rosidl_typesupport_introspection_c
rosidl_typesupport_introspection_cpp
rpyutils
rqt_graph
rqt_gui
rqt_gui_py
rviz2
rviz_assimp_vendor
rviz_common
rviz_default_plugins
rviz_ogre_vendor
rviz_rendering
sensor_msgs
sensor_msgs_py
service_msgs
shape_msgs
shared_queues_vendor
spdlog_vendor
sqlite3_vendor
sros2
sros2_cmake
statistics_msgs
std_msgs
std_srvs
stereo_msgs
tango_icons_vendor
tf2
tf2_bullet
tf2_eigen
tf2_eigen_kdl
tf2_geometry_msgs
tf2_kdl
tf2_msgs
tf2_py
tf2_ros
tf2_ros_py
tf2_sensor_msgs
tf2_tools
tf_transformations
tinyxml2_vendor
tracetools
trajectory_msgs
type_description_interfaces
uncrustify_vendor
unique_identifier_msgs
urdf
urdf_parser_plugin
vision_msgs
vision_opencv
visualization_msgs
yaml_cpp_vendor
zstd_vendor

```
</details>


* Updated the default mount point from `/workspaces/ros2_ws` -> `/workspaces`
  By default the `ros2_ws` directory is not already created, wich causes the following issue:
  ```
  OCI runtime exec failed: exec failed: unable to start container process: chdir to cwd ("/home/marcello/workspaces/ros2_ws") set in config.json failed: no such file or directory: unknown
  ```

  But reading the [README](https://github.com/MRo47/ros2_tools/blob/main/ros2_dev_container/workspaces/README.md) in workspaces it appears to me that this is what you originally intended. 

### Notes

The cli still needs docker compose I guess. 
Not sure if some sort of basic install instructions should be included (for docker in general, to help newbies)

Should be something like this, very easy:

Check the official instructions: [Install Docker Engine on Ubuntu](https://docs.docker.com/engine/install/ubuntu/) first. The procedure should be this:

```bash
# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
# Add the repository to Apt sources:
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# Install docker
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

Post-installation steps [Linux post-installation steps for Docker Engine](https://docs.docker.com/engine/install/linux-postinstall/) :

```bash
sudo groupadd docker
sudo usermod -aG docker $USER
```


Nvidia is more difficult though...

### CODE REVIEW

**Comment by MRo47** [comment]
About the `ros2_ws` yes that was the intention. Will leave at workspaces for now, the readme should keep the directory.

**Comment by MRo47** [comment]
For docker engine maybe we just mention the line as u said
"Check the official instructions: [Install Docker Engine on Ubuntu](https://docs.docker.com/engine/install/ubuntu/) first."
before [README 1. Dockerfile](https://github.com/MRo47/ros2_tools/tree/main/ros2_dev_container#1-dockerfile) .

Keeping the scope limited, and also maybe user should read more on dockers before touching this.

**Comment by mcarfagno** [comment]
> Keeping the scope limited, and also maybe user should read more on dockers before touching this. 

I agree TBH

**Comment by MRo47** [comment]
> For docker engine maybe we just mention the line as u said "Check the official instructions: [Install Docker Engine on Ubuntu](https://docs.docker.com/engine/install/ubuntu/) first." before [README 1. Dockerfile](https://github.com/MRo47/ros2_tools/tree/main/ros2_dev_container#1-dockerfile) .

@mcarfagno mind adding that line there?

**Review by MRo47 — APPROVED** [review]
Awesome, thanks for this.

**Pull request merged**
